version: '3.9'
services:
  player-one:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file: player1.env
    volumes:
      - './src:/app/src'
  player-two:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    env_file: player2.env
    volumes:
      - './src:/app/src'
